import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import type { HttpCall, HttpResult } from '../../programs/api-client/policy.js';

/**
 * A transport that behaves like App Store Connect where it matters for ownership binding:
 * - paths and methods come from Apple's OpenAPI spec (apple-openapi-paths.json, generated by
 *   scripts/apple-spec-paths.py). Unknown path → 404, method not in spec → 405.
 * - include values and filter names are validated against the spec → 400 otherwise.
 * - relationships.X.data is only present when X was included (as Apple does), and resources only
 *   carry relationships Apple defines. No invented relationships.app.
 * - /apps/{id}/appEvents ignores filter[id], as the live API does (see r3-live-events probe).
 */

interface SpecPath {
    methods: string[];
    include?: string[];
    filter?: string[];
    /** Relationship names a create/update body must include. */
    relationships?: string[];
}

const SPEC = JSON.parse(readFileSync(fileURLToPath(new URL('./apple-openapi-paths.json', import.meta.url)), 'utf8')) as {
    specVersion: string;
    paths: Record<string, SpecPath>;
};

const TEMPLATES = Object.keys(SPEC.paths).map((template) => ({
    template,
    parts: template.split('/').slice(1),
}));

export interface AppleWorld {
    /** appId → event ids. */
    apps?: Record<string, { events?: string[] }>;
    versions?: Record<string, { app: string; phasedRelease?: string }>;
    versionLocalizations?: Record<string, { version: string }>;
    screenshotSets?: Record<string, { versionLocalization?: string; cppLocalization?: string; screenshots?: string[] }>;
    cppLocalizations?: Record<string, { cppVersion: string }>;
    cppVersions?: Record<string, { cpp: string }>;
    cpps?: Record<string, { app: string }>;
    reviews?: Record<string, { response?: string; app?: string }>;
    users?: Record<string, { username?: string; email?: string }>;
}

const API = 'https://api.appstoreconnect.apple.com/v1';

function error(status: number, code: string, detail: string): HttpResult {
    return { status, headers: {}, data: { errors: [{ status: String(status), code, title: code, detail }] } };
}

export function matchSpec(path: string): { template: string; params: string[] } | undefined {
    const parts = path.split('?')[0]!.split('/').slice(1);
    let best: { template: string; params: string[]; literals: number } | undefined;
    for (const candidate of TEMPLATES) {
        if (candidate.parts.length !== parts.length) continue;
        const params: string[] = [];
        let literals = 0;
        let ok = true;
        for (let i = 0; i < parts.length; i++) {
            const want = candidate.parts[i]!;
            if (want.startsWith('{')) params.push(decodeURIComponent(parts[i]!));
            else if (want === parts[i]) literals += 1;
            else {
                ok = false;
                break;
            }
        }
        if (ok && (!best || literals > best.literals)) best = { template: candidate.template, params, literals };
    }
    return best && { template: best.template, params: best.params };
}

/** Spec-level checks only. Returns an error result or undefined when the call is valid. */
export function specViolation(call: HttpCall): HttpResult | undefined {
    const path = call.url.startsWith(API) ? call.url.slice(API.length) : call.url;
    const matched = matchSpec(path);
    if (!matched) return error(404, 'NOT_FOUND', 'The path provided does not match a defined resource type.');
    const spec = SPEC.paths[matched.template]!;
    if (!spec.methods.includes(call.method)) return error(405, 'METHOD_NOT_ALLOWED', `${call.method} is not allowed on ${matched.template}`);
    if (call.method === 'POST' || call.method === 'PATCH') {
        const raw = call.data as { data?: unknown } | null | undefined;
        if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
            return error(400, 'ENTITY_ERROR', 'Expected a JSON:API document');
        }
        if (Array.isArray(raw.data)) {
            const bad = raw.data.some((item) => {
                const row = item as { type?: unknown; id?: unknown } | null;
                return !row || typeof row.type !== 'string' || typeof row.id !== 'string';
            });
            if (bad) return error(400, 'ENTITY_ERROR', 'relationship linkage requires type and id');
        } else {
            const data = raw.data as { type?: unknown; attributes?: unknown; relationships?: Record<string, unknown> } | null;
            if (!data || typeof data !== 'object') return error(400, 'ENTITY_ERROR', 'data is required');
            if (typeof data.type !== 'string' || !data.type) return error(400, 'ENTITY_ERROR', 'data.type is required');
            if (!data.attributes || typeof data.attributes !== 'object' || Array.isArray(data.attributes)) {
                return error(400, 'ENTITY_ERROR', 'data.attributes is required');
            }
            for (const name of spec.relationships ?? []) {
                if (!data.relationships?.[name]) return error(400, 'ENTITY_ERROR', `relationships.${name} is required`);
            }
        }
    }
    if (call.method === 'GET') {
        const query = path.split('?')[1] ?? '';
        const fromUrl: Record<string, string> = {};
        for (const part of query.split('&')) {
            if (!part) continue;
            const eq = part.indexOf('=');
            const rawKey = eq === -1 ? part : part.slice(0, eq);
            const rawValue = eq === -1 ? '' : part.slice(eq + 1);
            fromUrl[decodeURIComponent(rawKey)] = decodeURIComponent(rawValue);
        }
        const bags = [fromUrl, call.params ?? {}];
        for (const bag of bags) {
            for (const [key, value] of Object.entries(bag)) {
                if (key === 'include') {
                    for (const name of String(value).split(',')) {
                        if (name && !spec.include?.includes(name)) {
                            return error(400, 'PARAMETER_ERROR.INVALID', `'${name}' is not a valid relationship name`);
                        }
                    }
                }
                const filter = /^filter\[(.+)\]$/.exec(key);
                if (filter && !spec.filter?.includes(filter[1]!)) {
                    return error(400, 'PARAMETER_ERROR.INVALID', `'${filter[1]}' is not a valid filter type`);
                }
            }
        }
    }
    return undefined;
}

function includes(call: HttpCall): Set<string> {
    const raw = call.params?.include;
    return new Set(raw ? String(raw).split(',') : []);
}

function resource(type: string, id: string, rels: Record<string, { type: string; id?: string }>, call: HttpCall, attributes: Record<string, unknown> = {}) {
    const wanted = includes(call);
    const relationships: Record<string, unknown> = {};
    for (const [key, target] of Object.entries(rels)) {
        relationships[key] = wanted.has(key)
            ? { data: target.id ? { type: target.type, id: target.id } : null, links: {} }
            : { links: {} };
    }
    return { status: 200, headers: {}, data: { data: { type, id, attributes, relationships } } } as HttpResult;
}

const notFound = () => error(404, 'NOT_FOUND', 'There is no resource with this id.');

/** Data for the GETs the ownership binding and the write planners perform. */
function answer(call: HttpCall, world: AppleWorld): HttpResult {
    const path = call.url.startsWith(API) ? call.url.slice(API.length) : call.url;
    const { template, params } = matchSpec(path)!;
    const [first] = params;
    const id = first ?? '';
    switch (template) {
        case '/appStoreVersions/{id}': {
            const v = world.versions?.[id];
            if (!v) return notFound();
            return resource('appStoreVersions', id, {
                app: { type: 'apps', id: v.app },
                appStoreVersionPhasedRelease: { type: 'appStoreVersionPhasedReleases', id: v.phasedRelease },
            }, call);
        }
        case '/appStoreVersionLocalizations/{id}': {
            const loc = world.versionLocalizations?.[id];
            if (!loc) return notFound();
            return resource('appStoreVersionLocalizations', id, { appStoreVersion: { type: 'appStoreVersions', id: loc.version } }, call);
        }
        case '/appScreenshotSets/{id}': {
            const set = world.screenshotSets?.[id];
            if (!set) return notFound();
            const out = resource('appScreenshotSets', id, {
                appStoreVersionLocalization: { type: 'appStoreVersionLocalizations', id: set.versionLocalization },
                appCustomProductPageLocalization: { type: 'appCustomProductPageLocalizations', id: set.cppLocalization },
            }, call);
            if (includes(call).has('appScreenshots')) {
                (out.data as any).data.relationships.appScreenshots = {
                    data: (set.screenshots ?? []).map((shot) => ({ type: 'appScreenshots', id: shot })),
                };
            }
            return out;
        }
        case '/appStoreVersionLocalizations/{id}/appScreenshotSets': {
            const sets = Object.entries(world.screenshotSets ?? {}).filter(([, set]) => set.versionLocalization === id);
            return {
                status: 200,
                headers: {},
                data: {
                    data: sets.map(([setId, set]) => ({
                        type: 'appScreenshotSets',
                        id: setId,
                        relationships: { appScreenshots: { data: (set.screenshots ?? []).map((shot) => ({ type: 'appScreenshots', id: shot })) } },
                    })),
                },
            };
        }
        case '/appCustomProductPageLocalizations/{id}': {
            const loc = world.cppLocalizations?.[id];
            if (!loc) return notFound();
            return resource('appCustomProductPageLocalizations', id, {
                appCustomProductPageVersion: { type: 'appCustomProductPageVersions', id: loc.cppVersion },
            }, call);
        }
        case '/appCustomProductPageVersions/{id}': {
            const version = world.cppVersions?.[id];
            if (!version) return notFound();
            return resource('appCustomProductPageVersions', id, { appCustomProductPage: { type: 'appCustomProductPages', id: version.cpp } }, call);
        }
        case '/appCustomProductPages/{id}': {
            const cpp = world.cpps?.[id];
            if (!cpp) return notFound();
            return resource('appCustomProductPages', id, { app: { type: 'apps', id: cpp.app } }, call);
        }
        case '/apps/{id}/customerReviews': {
            const reviews = Object.entries(world.reviews ?? {}).filter(([, review]) => review.app === id);
            return {
                status: 200,
                headers: {},
                data: { data: reviews.map(([reviewId]) => ({ type: 'customerReviews', id: reviewId })), links: {} },
            };
        }
        case '/apps/{id}/appEvents': {
            // Apple ignores filter[id] on this endpoint: always the whole list.
            const events = world.apps?.[id]?.events ?? [];
            return { status: 200, headers: {}, data: { data: events.map((event) => ({ type: 'appEvents', id: event })), links: {} } };
        }
        case '/customerReviews/{id}':
            if (!world.reviews?.[id]) return notFound();
            return resource('customerReviews', id, { response: { type: 'customerReviewResponses', id: world.reviews[id]!.response } }, call);
        case '/customerReviews/{id}/response': {
            const response = world.reviews?.[id]?.response;
            if (!response) return notFound();
            return { status: 200, headers: {}, data: { data: { type: 'customerReviewResponses', id: response } } };
        }
        case '/users/{id}': {
            const user = world.users?.[id];
            if (!user) return notFound();
            return { status: 200, headers: {}, data: { data: { type: 'users', id, attributes: user } } };
        }
        default:
            return { status: 200, headers: {}, data: { data: [] } };
    }
}

export function appleTransport(world: AppleWorld, calls: HttpCall[] = []) {
    return {
        calls,
        async send(call: HttpCall): Promise<HttpResult> {
            calls.push(call);
            const violation = specViolation(call);
            if (violation) return violation;
            if (call.method === 'GET') return answer(call, world);
            if (call.method === 'DELETE') return { status: 204, headers: {}, data: undefined };
            if (call.method === 'POST') {
                return {
                    status: 201,
                    headers: {},
                    data: {
                        data: {
                            id: 'created-1',
                            attributes: {
                                uploadOperations: [{ method: 'PUT', url: 'http://127.0.0.1:1/part', offset: 0, length: 1 }],
                            },
                        },
                    },
                };
            }
            return { status: 200, headers: {}, data: { data: { id: 'patched-1' } } };
        },
    };
}
